### ISSUE TITLE
Editable Linked Checklist

### ISSUE THREAD

**Issue by theMackabu** [sajjaadf/Mice-And-Men-Mock-Trial#2]
# _Of Mice And Men_ Mock Trial 
### Checklist
- [x] Decide what charge(s) to charge Lennie Small and inform the defendant and defense team before the next class. 
- [X] Decide which witnesses to call to the stand and notify the witnesses.
- [X] Meet with each witness before the mock trial begins to prep them for the trial. 
- [ ] Write opening statement essay with an introduction and two body paragraphs that give claims, evidence and reasoning for why Lennie Small should be found guilty.
- [ ] Develop a specific list of questions for each witness that the prosecution will call to the stand.
- [ ] Develop a specific list of cross examination questions for each witness the defense calls to the stand.
- [ ] Practice the questions and answers with the witnesses. Be sure they are ready to be cross-examined as well.
- [ ] Prepare a closing statement.
- [ ] Rehearse your opening and closing statements.
### Witness Checklist
- [X] Decide which witnesses to call to the stand and notify the witnesses.
- [X] Meet with each witness before the mock trial begins to prep them for the trial. 
- [ ] Develop a specific list of questions for each witness that the prosecution will call to the stand.
- [ ] Develop a specific list of cross examination questions for each witness the defense calls to the stand.
- [ ] Practice the questions and answers with the witnesses. Be sure they are ready to be cross-examined as well.
